Feacture 09 02 2023 ab account page
marmetodevelopers/Milton pull request #10
Opened 2024-02-14 12:15 UTC by Balaji-agidigalla

Pull Request (PR) Request Template:

### Problem
<Provide a brief overview of the problem or task that this PR addresses.>
1. Profile page setup - Current page looks very basic and scattered, we need align everything properly

Monday Card Link: [<https://marmeto-force.monday.com/boards/5966670929/pulses/6025395742>]

### Solution
<Briefly describe what was implemented and how it solves the problem.>
i have refered the other websites account page and i just make changes on current theme

<Visual representation or screenshots>
![image](https://github.com/marmetodevelopers/Milton/assets/130204053/bf601ff6-add8-4f87-b103-c9faf01bed2a)

### Impacted Areas
<Explain other areas of the application that could be affected by this change.>
Account Page 

### Done Checklist
- [x] Performed unit testing to ensure functionality and identify potential issues.
- [x] Followed basic code standards and best practices. (indentation, media queries, basic customizer things)
- [x] Added comments to explain complex logic or improve code readability.
- [x] Followed Naming conventions and proper variable declaration.
- [x] Handled edge cases and errors gracefully to prevent crashes.
- [x] Optimized the code for production to ensure performance.

Please review this PR and provide feedback. Thank you!

2024-02-14 13:18 UTC, arshiya-khanam requested changes

2024-02-14 13:18 UTC, arshiya-khanam commented on assets/account-page-tabs.js
> +  for (i = 0; i < tabContents.length; i++) {
you can use forEach than doing forloop

2024-02-14 13:18 UTC, arshiya-khanam commented on assets/account-page-tabs.js
> +  for (i = 0; i < tabLinks.length; i++) {
you can use forEach than doing forloop

2024-02-14 13:18 UTC, arshiya-khanam commented on assets/account-page-tabs.js
> +  for (var i = 0; i < tabLinks.length; i++) {
you can use forEach than doing forloop

2024-02-14 13:18 UTC, arshiya-khanam commented on templates/customers/order.liquid
> +            {% comment %} <th>{{ 'customer.order.sku' | t }}</th> {% endcomment %}
remove unwanted code

2024-02-14 13:18 UTC, arshiya-khanam commented on templates/customers/order.liquid
> +            {% comment %} <td data-label="{{ 'customer.order.sku' | t }}">{{ line_item.sku }}</td> {% endcomment %}
remove unwanted code

2024-02-14 13:47 UTC, arshiya-khanam approved these changes

2024-02-16 09:52 UTC, Manuraj-Marmeto approved these changes

2024-02-16 09:53 UTC, merged